### ISSUE TITLE
pseudo matched-normal

### ISSUE THREAD

**Issue by yifnzhao** [raphael-group/chisel#14] opened 2020-10-07 15:40 UTC
Hi CHISEL developers,

Thanks very much for developing this tool and for the helpful documentation. I encountered a problem when I tried to generate a pseudo matched-normal sample.  And here is the error that I am getting:

```  
File "/home/.conda/envs/chisel/bin/chisel_pseudonormal", line 10, in <module>
    sys.exit(main())
File "/home/.conda/envs/chisel/lib/python2.7/site-packages/bin/chisel_pseudonormal.py", line 108, in main
    total = reduce(inupdate, (Counter(counts[c][b]) for c in counts for b in counts[c]))
TypeError: reduce() of empty sequence with no initial value
```
It looks like in the [counting_cells](https://github.com/raphael-group/chisel/blob/963d61ea5fa1c511dcf96b9c2cfcd66c7b96eda7/src/RDREstimator.py#L173) function, somehow _rd_ is always ' ', and _counts_ does not get updated. 

However, when I counted the mapped reads in the bam file (using command `samtools view -c sample.bam`, I got the number 5402525.

Do you by any chance know what might have gone wrong? Thanks!

Very best,
Yifan

**Comment by simozacca** [comment] 2020-10-08 18:00
Hi,

Thank you for the interest in CHISEL, I will be glad to help you with this issue. At first glance, there are two potential issues, please see the comments here below:

1. `chisel_pseudonormal` selects cells as barcodes that have a minimum number of reads, specified by the flag option `-m` and whose default value is 100,000 reads. All barcodes with fewer number of reads will be discarded, and if there is no remaining cell this could be the cause of the error (we will fix this behavior in the next release). Thus, could you please confirm that your cells are expected to have >100,000 reads? If this is not the case please select a lower minimum value with `-m`. Also, for the purpose of debugging, could you please try to run the command using `-m 1`, so we make sure that this is not the issue?

2. Could you please confirm what is the format of the barcodes in your barcoded BAM file? Specifically, it would be very helpful if you could please report here the first 5-10 reads in your BAM files, for example could you please report here the output of the command
```
samtools view ${BAM} | head -n 10
```

Thank you

**Comment by yifnzhao** [comment] 2020-10-08 18:10
Hi,

Thanks for your prompt reply!
1. I have tried `-m 1` and also adjusting the threshold and bin sizes. But none of those seems to resolve the issue. I still got the same error message.
2. Please find the bam head here: [bamhead.txt](https://github.com/raphael-group/chisel/files/5350529/bamhead.txt).

Thanks again!

**Comment by simozacca** [comment] 2020-10-08 18:32
Thanks for this information.

It seems that the issue is that your BAM file does not have the barcodes in the format [required](https://github.com/raphael-group/chisel#requireddata) by CHISEL.

CHISEL requires that the barcode of each cell is a string or a substring of the form `CB:Z:[A,C,G,T]+`, i.e. starting with `CB:Z:` and then a string **only** composed of characters `A,C,G,T`. You can also add the barcode as part of the `RG` flag as `RG:Z:CB:Z:[A,C,G,T]+`. Note that in the next release that is about to come out `CB:Z:` can be substituted with any other string. We will also consider in future releases to relax the constraint of the barcode being only composed of `A,C,G,T`.

Your barcodes seem to be encoded in the `RG:` flag with a different format, for example `RG:Z:GliaLC-5-C8_RG`. Thus, you should change your barcodes to fit the required format, for example using the procedure reported here below from #12 or following the instructions provided in #9 

> Thanks for the provided information!
> 
> The problem is that CHISEL requires each cell barcode to be a string only composed of the letters `A,C,G,T` preceded by `CB:Z:` (see details in [required data](https://github.com/raphael-group/chisel#requireddata)). Thus, the cell barcode `RG:Z:CB:Z:TFRIPAIR4_FL-A98167-R09-C26` in your example is not a valid barcode, while `RG:Z:CB:Z:TATTGGCA` would be.
> 
> You can generate an arbitrary list of 800 cell barcodes of 8 letters with the following script:
> 
> ```
> for BARCODE in {A,C,G,T}{A,C,G,T}{A,C,G,T}{A,C,G,T}{A,C,G,T}{A,C,G,T}{A,C,G,T}{A,C,G,T}; do echo "CB:Z:"${BARCODE}; done | shuf -n 800
> ```
> 
> and you can use these barcodes for your cells. Using these barcodes instead of the current names in your `barcodes.txt` everything should work correctly. Also, if `barcodes.txt` contains file names you can append the barcodes as a second column of the file and in the command you can simply use the first field of each line as the file name and the second field as the barcode to add as an RG flag.
> 
> Just one additional note, I think that you may need `${1}` instead of `${i}` in your function `cust_func()` to access the first argument.
> 
> Please let me know if this procedure would work for you and if you have any further question.

**Comment by yifnzhao** [comment] 2020-10-09 19:14
Thanks for your suggestion. Unfortunately adding barcodes did not work for my bam files. I will try to look if there are other inconsistencies wrt the 10x format, and update here if the issue gets resolved. Thanks again!

**Comment by yifnzhao** [comment] 2020-10-14 21:36
Hi Simone,

I tried playing around with the threshold, min read, and bin size, but I am still getting the same error message. I couldn't figure out what might have been wrong. Here are the top 30 lines from the bam file after adding the cell barcodes: [bamhead.txt](https://github.com/raphael-group/chisel/files/5380968/bamhead.txt). Could you help me look into it? Thanks!

Best,
Yifan

**Comment by simozacca** [comment] 2020-10-15 08:22
I have tested the CHISEL functions on your sample and everything seems to be working well. Could you please provide the full log of the CHISEL command when running with `-m 1`?

Also, it looks like that every barcode is the same in your BAM sample; does this mean that there is only one cell?

**Comment by yifnzhao** [comment] 2020-10-15 13:54
Here is the log: [log.txt](https://github.com/raphael-group/chisel/files/5385302/log.txt). I tried reinstalling CHISEl but still had the same error. 

Yes, I am currently using only one cell for testing purposes. Would that be a problem?

**Comment by simozacca** [comment] 2020-10-15 14:05
Do the chromosomes in your reference genome follow the `chr` or non-`chr` notation? Could you please report here the dictionary file of your reference genome?

Thank you

**Comment by yifnzhao** [comment] 2020-10-15 14:08
It follows non-chr notation. Here attaches the dictionary file: [human_g1k_v37_decoy.dict.txt](https://github.com/raphael-group/chisel/files/5385387/human_g1k_v37_decoy.dict.txt)

**Comment by simozacca** [comment] 2020-10-15 14:19
Could you please send to us the result of this command? We will investigate the issue locally.

```
samtools view -h ${BAM} | head -n 100
```

Thank you

**Comment by yifnzhao** [comment] 2020-10-15 14:24
Hi Please find the files attached:
[human_g1k_v37_decoy.dict.txt](https://github.com/raphael-group/chisel/files/5385466/human_g1k_v37_decoy.dict.txt)
[head100.txt](https://github.com/raphael-group/chisel/files/5385469/head100.txt)

The chromosomes follow non-chr notation.

Thanks!

**Comment by simozacca** [comment] 2020-10-15 15:00
We created a test BAM file using all the reads in your `bamhead` file and using the BAM header in the `head100` file; please find the resulting BAM file attached to this message with his index.

On this sample dataset, the following `CHISEL` command works correctly:
```
chisel_pseudonormal -r ${REF} test.bam -m 1
```

with the following output:
```
[2020-Oct-15 10:52:46]Parsing and checking arguments
[2020-Oct-15 10:52:46]Arguments:
        chromosomes : chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22
        reference : /n/fs/ragr-data/datasets/ref-genomes/GRCh37_NCBI/GRCh37.p13.dict
        normal : pseudonormal.bam
        jobs : 56
        rundir : ./
        tmpdir : ./_TMP
        samtools : samtools
        minreads : 1
        binsize : 5000000
        tumor : test.bam
        thres : 0.9

[2020-Oct-15 10:52:46]Computing bins
[2020-Oct-15 10:52:46]Counting reads on barcoded cells
Progress: |████████████████████████████████████████| 100.0% Complete [[2020-Oct-15 10:52:47]Extracted barcodes on 18:75000000-78077248]
[2020-Oct-15 10:52:47]Computing total numbers of sequenced reads
[2020-Oct-15 10:52:47]Selecting all cells to consider for the analysis
[2020-Oct-15 10:52:47]Number of selected cells: 1
[2020-Oct-15 10:52:47]Selecting diploid cells
[2020-Oct-15 10:52:47]Number of identified diploid cells: 1
[2020-Oct-15 10:52:47]Approximate sequencing coverage of pseudo matched-normal sample: 0.00018
[2020-Oct-15 10:52:47]Extracting sequencing reads from selected diploid cells
[2020-Oct-15 10:52:47]Merging and extracted sequencing reads and indexing the output pseduo matched-normal sample
[2020-Oct-15 10:52:47]Removing temporary files
[2020-Oct-15 10:52:47]KTHXBYE
```

After decompressing the attached files with `gzip`, could you please try to replicate the same run and let us know if it works for you and with your reference genome?

Thank you

[test.bam.gz](https://github.com/raphael-group/chisel/files/5385759/test.bam.gz)
[test.bam.bai.gz](https://github.com/raphael-group/chisel/files/5385760/test.bam.bai.gz)

**Comment by yifnzhao** [comment] 2020-10-15 15:06
Yes the test.bam works for me with my ref genome! I didn't quite understand - could you explain the difference between the test.bam and my bam file?

**Comment by simozacca** [comment] 2020-10-15 16:29
Your "BAM file" `head100.txt` only contains sequencing reads with mapping quality of 0, that thus get discarded.

**Comment by yifnzhao** [comment] 2020-10-15 20:08
I see. I also found that there was some issue with the index file generation. Now it is working perfectly. Thanks very much for your help! 

I have another question regarding the generation of pseudo matched-normal sample: does it require all cells to be from the same individual, and how many cells are required approximately? Thanks!

**Comment by simozacca** [comment] 2020-10-16 08:47
Yes, by definition a matched-normal sample is composed of normal diploid cells from the same individual as tumor cells; this is essential to identify germline heterozygous SNPs that are specific to the cancer patient.

The minimum number of cells for forming a matched-normal sample depends on what is the sequencing coverage per cell in your data. Thus, the absolute number of diploid cells is not the quantity that really matters but the resulting sequencing coverage of the matched-normal sample is. The CHISEL command outputs this value that you can evaluate: based on previous experiences, ~10x is the minimum to obtain accurate results and lower values should be evaluated on a per-case basis, ~30x is the ideal value, and >30x allow to get the highest quality results.

As the error seems to be solved, I am closing the issue for now, but please feel free to re-open it in case of related errors.

**Closed as completed by simozacca** 2020-10-16 08:47 UTC
